# Generated by Django 4.2.1 on 2023-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleduy_blog', '0002_post_work_hours_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default='', help_text='Не более 150 символов', max_length=150, verbose_name='Краткое описание'),
        ),
    ]
