# Generated by Django 4.2.1 on 2023-05-25 11:55

from django.db import migrations, models
import django.db.models.deletion
import sleduy_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('sleduy_blog', '0003_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.CharField(default='', help_text='Максимум 150 символов', max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=sleduy_blog.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sleduy_blog.post')),
            ],
        ),
    ]
